"""
Quality models - scoring, patterns, and improvement tracking
"""
from sqlalchemy import Column, String, DateTime, Text, Integer, Float, JSON, ForeignKey, Boolean, Date, UniqueConstraint
from sqlalchemy.sql import func
from app.database import Base
import uuid


class QualityScore(Base):
    """
    Per-message quality scores across 5 dimensions.
    Generated async by the Quality Scorer (LLM-as-judge) after response is delivered.
    """
    __tablename__ = "quality_scores"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False)
    message_id = Column(String(36), nullable=False, index=True)
    channel = Column(String(20), nullable=False, default="web_chatbot")

    # 5 quality dimensions (0.0 - 1.0)
    relevance = Column(Float, nullable=True)
    accuracy = Column(Float, nullable=True)
    completeness = Column(Float, nullable=True)
    conciseness = Column(Float, nullable=True)
    tone = Column(Float, nullable=True)
    overall_score = Column(Float, nullable=False)

    # Judge metadata
    judge_model = Column(String(255), nullable=True)
    judge_latency_ms = Column(Integer, nullable=True)

    # Analysis
    flaws = Column(JSON, nullable=True)
    suggestions = Column(Text, nullable=True)

    created_at = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<QualityScore(id={self.id}, overall={self.overall_score})>"


class FailurePattern(Base):
    """
    Clustered patterns of poor-quality responses. Generated by the Pattern Detector.
    Groups similar failures by topic, intent, or failure type.
    """
    __tablename__ = "failure_patterns"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False)
    channel = Column(String(20), nullable=False, default="web")

    pattern_name = Column(String(255), nullable=False)
    pattern_type = Column(String(50), nullable=False)
    description = Column(Text, nullable=True)

    cluster_keywords = Column(JSON, nullable=True)
    sample_queries = Column(JSON, nullable=True)
    message_ids = Column(JSON, nullable=True)

    message_count = Column(Integer, default=0)
    avg_score = Column(Float, nullable=True)
    impact_score = Column(Float, nullable=True)
    is_actionable = Column(Boolean, default=True)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<FailurePattern(id={self.id}, type={self.pattern_type}, count={self.message_count})>"


class ImprovementCandidate(Base):
    """
    Before/after comparison for admin review. Generated by the Shadow Evaluator
    when a variant outperforms the production response by a significant margin.
    """
    __tablename__ = "improvement_candidates"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False)
    message_id = Column(String(36), nullable=False)
    channel = Column(String(20), nullable=False)

    user_query = Column(Text, nullable=False)
    original_response = Column(Text, nullable=False)
    original_score = Column(Float, nullable=False)
    original_flaws = Column(JSON, nullable=True)

    optimized_response = Column(Text, nullable=True)
    optimized_score = Column(Float, nullable=True)
    improvement_delta = Column(Float, nullable=True)

    improvement_type = Column(String(50), nullable=False)
    variant_config = Column(JSON, nullable=True)

    status = Column(String(20), nullable=False, default="pending")
    reviewed_by = Column(String(255), nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    review_notes = Column(Text, nullable=True)
    deployed_at = Column(DateTime, nullable=True)

    created_at = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<ImprovementCandidate(id={self.id}, delta={self.improvement_delta}, status={self.status})>"


class QualityMetric(Base):
    """
    Aggregated daily/weekly/metric quality rollups for dashboard charts.
    Populated by the daily rollup job.
    """
    __tablename__ = "quality_metrics"
    __table_args__ = (
        # One metric per tenant per date per period
        UniqueConstraint('tenant_id', 'metric_date', 'period', name='uq_quality_metric_tenant_date_period'),
    )

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False)

    metric_date = Column(Date, nullable=False)
    period = Column(String(10), nullable=False, default="day")

    total_messages = Column(Integer, default=0)
    avg_overall_score = Column(Float, nullable=True)
    avg_relevance = Column(Float, nullable=True)
    avg_accuracy = Column(Float, nullable=True)
    avg_completeness = Column(Float, nullable=True)
    avg_conciseness = Column(Float, nullable=True)
    avg_tone = Column(Float, nullable=True)

    low_score_count = Column(Integer, default=0)
    high_score_count = Column(Integer, default=0)

    feedback_positive = Column(Integer, default=0)
    feedback_negative = Column(Integer, default=0)

    failure_patterns_detected = Column(Integer, default=0)
    improvements_applied = Column(Integer, default=0)

    created_at = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<QualityMetric(date={self.metric_date}, period={self.period}, avg={self.avg_overall_score})>"
