"""
Before/After Generator Service

Creates structured comparison cards for admin review. Each card shows:
  - What the user asked
  - What the bot actually said (before)
  - What the bot COULD have said (after)
  - Quality scores for both
  - Specific flaws identified
  - Improvement type and expected impact

Cards are derived from ImprovementCandidate records generated by the Shadow Evaluator.
"""
import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List, Optional
from sqlalchemy.orm import Session

from app.models.quality import ImprovementCandidate, QualityScore
from app.models.chat import ChatMessage

logger = logging.getLogger(__name__)


def generate_comparison_card(
    candidate: ImprovementCandidate,
) -> Dict[str, Any]:
    """
    Build a structured before/after comparison from an ImprovementCandidate.
    Returns a dict suitable for API response and dashboard rendering.
    """
    improvement_type_labels = {
        "prompt_tweak": "Prompt Optimization",
        "kb_addition": "Knowledge Base Addition",
        "config_change": "Configuration Change",
        "model_change": "Model Change",
    }

    status_labels = {
        "pending": "Awaiting Review",
        "approved": "Approved",
        "rejected": "Rejected",
        "deployed": "Deployed",
    }

    delta = candidate.improvement_delta or 0.0
    if delta >= 0.20:
        impact_label = "High Impact"
        impact_level = "high"
    elif delta >= 0.10:
        impact_label = "Medium Impact"
        impact_level = "medium"
    else:
        impact_label = "Low Impact"
        impact_level = "low"

    variant_config = candidate.variant_config or {}
    variant_name = variant_config.get("variant_name", "unknown")
    variant_desc = variant_config.get("description", "")

    return {
        "id": candidate.id,
        "tenant_id": candidate.tenant_id,
        "message_id": candidate.message_id,
        "channel": candidate.channel,
        "created_at": candidate.created_at.isoformat() if candidate.created_at else None,
        "user_query": candidate.user_query,
        "before": {
            "response": candidate.original_response,
            "score": candidate.original_score,
            "flaws": candidate.original_flaws or [],
        },
        "after": {
            "response": candidate.optimized_response or "",
            "score": candidate.optimized_score or 0.0,
        },
        "improvement": {
            "delta": round(delta, 4),
            "delta_pct": round(delta * 100, 1),
            "type": candidate.improvement_type,
            "type_label": improvement_type_labels.get(
                candidate.improvement_type, candidate.improvement_type
            ),
            "variant_name": variant_name,
            "variant_description": variant_desc,
            "impact_label": impact_label,
            "impact_level": impact_level,
        },
        "status": candidate.status,
        "status_label": status_labels.get(candidate.status, candidate.status),
        "reviewed_by": candidate.reviewed_by,
        "reviewed_at": candidate.reviewed_at.isoformat() if candidate.reviewed_at else None,
        "review_notes": candidate.review_notes,
    }


def get_pending_candidates(
    db: Session,
    tenant_id: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
) -> List[Dict[str, Any]]:
    """
    Get pending improvement candidates, ordered by improvement delta (highest first).
    """
    query = db.query(ImprovementCandidate).filter(
        ImprovementCandidate.status == "pending"
    )

    if tenant_id:
        query = query.filter(ImprovementCandidate.tenant_id == tenant_id)

    candidates = (
        query
        .order_by(ImprovementCandidate.improvement_delta.desc().nullslast())
        .offset(offset)
        .limit(limit)
        .all()
    )

    return [generate_comparison_card(c) for c in candidates]


def get_candidate_history(
    db: Session,
    tenant_id: Optional[str] = None,
    limit: int = 50,
    offset: int = 0,
) -> List[Dict[str, Any]]:
    """
    Get historical (approved/rejected) candidates.
    """
    query = db.query(ImprovementCandidate).filter(
        ImprovementCandidate.status.in_(["approved", "rejected", "deployed"])
    )

    if tenant_id:
        query = query.filter(ImprovementCandidate.tenant_id == tenant_id)

    candidates = (
        query
        .order_by(ImprovementCandidate.reviewed_at.desc().nullslast())
        .offset(offset)
        .limit(limit)
        .all()
    )

    return [generate_comparison_card(c) for c in candidates]


def approve_candidate(
    db: Session,
    candidate_id: str,
    reviewed_by: str,
    review_notes: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """
    Approve an improvement candidate.
    Marks it for deployment in the next self-learning cycle.
    """
    candidate = db.query(ImprovementCandidate).filter(
        ImprovementCandidate.id == candidate_id
    ).first()

    if not candidate:
        return None

    candidate.status = "approved"
    candidate.reviewed_by = reviewed_by
    candidate.reviewed_at = datetime.now(timezone.utc)
    if review_notes:
        candidate.review_notes = review_notes

    db.commit()
    db.refresh(candidate)

    logger.info(
        f"[BeforeAfter] Candidate {candidate_id} approved by {reviewed_by}"
    )

    return generate_comparison_card(candidate)


def reject_candidate(
    db: Session,
    candidate_id: str,
    reviewed_by: str,
    review_notes: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """
    Reject an improvement candidate.
    """
    candidate = db.query(ImprovementCandidate).filter(
        ImprovementCandidate.id == candidate_id
    ).first()

    if not candidate:
        return None

    candidate.status = "rejected"
    candidate.reviewed_by = reviewed_by
    candidate.reviewed_at = datetime.now(timezone.utc)
    if review_notes:
        candidate.review_notes = review_notes

    db.commit()
    db.refresh(candidate)

    logger.info(
        f"[BeforeAfter] Candidate {candidate_id} rejected by {reviewed_by}: {review_notes}"
    )

    return generate_comparison_card(candidate)


def get_candidate_summary(
    db: Session,
    tenant_id: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Get summary counts of candidate statuses.
    """
    query = db.query(ImprovementCandidate)

    if tenant_id:
        query = query.filter(ImprovementCandidate.tenant_id == tenant_id)

    total = query.count()
    pending = query.filter(ImprovementCandidate.status == "pending").count()
    approved = query.filter(ImprovementCandidate.status == "approved").count()
    rejected = query.filter(ImprovementCandidate.status == "rejected").count()
    deployed = query.filter(ImprovementCandidate.status == "deployed").count()

    # Average improvement delta for approved candidates
    approved_query = query.filter(ImprovementCandidate.status.in_(["approved", "deployed"]))
    avg_delta = 0.0
    if approved_query.count() > 0:
        from sqlalchemy import func
        avg_delta = approved_query.with_entities(
            func.avg(ImprovementCandidate.improvement_delta)
        ).scalar() or 0.0

    return {
        "total": total,
        "pending": pending,
        "approved": approved,
        "rejected": rejected,
        "deployed": deployed,
        "avg_improvement_delta": round(float(avg_delta), 4),
    }
